// <auto-generated />
using System;
using Library_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240913113427_Update book DATETIME")]
    partial class UpdatebookDATETIME
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_API.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvalible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Author = "Alice Johansson",
                            Description = "A journey through a mysterious world hidden beneath the earth's surface, filled with ancient magic and forgotten creatures.",
                            Genre = "Fantasy",
                            IsAvalible = true,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Phantom Abyss"
                        },
                        new
                        {
                            Id = 102,
                            Author = "Liam Eriksson",
                            Description = "A small town is haunted by strange voices that echo through the night, leading its residents to unravel a chilling secret.",
                            Genre = "Horror",
                            IsAvalible = false,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Whispers in the Dark"
                        },
                        new
                        {
                            Id = 103,
                            Author = "Sofia Lundgren",
                            Description = "In a distant future, humanity must explore uncharted galaxies to find new habitable planets, but they are not alone.",
                            Genre = "Science Fiction",
                            IsAvalible = true,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Galactic Frontiers"
                        },
                        new
                        {
                            Id = 104,
                            Author = "Oskar Nilsson",
                            Description = "Set during World War II, a young woman uncovers a long-lost family secret that changes her life forever.",
                            Genre = "Historical Fiction",
                            IsAvalible = false,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Echoes of the Past"
                        },
                        new
                        {
                            Id = 105,
                            Author = "Nina Bergström",
                            Description = "A brilliant scientist's groundbreaking discovery threatens to disrupt the fabric of reality, and now everyone is after it.",
                            Genre = "Thriller",
                            IsAvalible = true,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Quantum Enigma"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
